### ISSUE TITLE
Surge token resources not displaying as options

### ISSUE THREAD

**Issue by Jefferydo** [johnnolan/wild-magic-surge-5e#459]
In the token Resource tab, the list of Bar 2 Attribute options doesn't include resources.wmsurgedescending or resources.wmsurgeincrement.

Foundry v10.291

![image](https://user-images.githubusercontent.com/11779859/212503288-5ba113fe-029d-4c45-a2c0-270c9c8781a3.png)

**Comment by johnnolan** [comment]
The new DataModel changes in 5e system seem to stop allowing custom resources being set.

I will keep looking through the docs for alternative ways, otherwise I may need to change tactics and provide an option to allow a player to set one of their resources to be handled by the module. Feels too intrusive but that may be the only way.

**Comment by johnnolan** [comment]
Also investigate stability of [Bar Crawl](https://gitlab.com/woodentavern/foundryvtt-bar-brawl) and whether I can use that as a optional dependency instead as a last resort :(

**Comment by johnnolan** [comment]
## Solution

* Remove updating custom resource flag
* Add setting to choose which resource to update, primary, secondary or tertiary
* Change logic so both Incremental and Descending use that Actor resource
* This can then be set in the token resource but will also appear in the character sheet

Downsides will mean that the actor will need to have one of these set which won't work if they already use all three resources.
