### ISSUE TITLE
Undefined Behaviour for Spell Level Dependant mode, and Cantrips enabled

### ISSUE THREAD

**Issue by linxcat** [johnnolan/wild-magic-surge-5e#489]
Cantrips are zero level spells. It stands to reason that they should be capable of having their own formula in the configuration menu for Spell Level Dependant Surges. However, this isn't possible. I assume they're coded to copy level 1? That isn't strictly correct, and should be definable.

**Comment by linxcat** [comment]
I personally want them to be rolled with advantage, checking for a 1, since <=0 is impossible. I don't think this is possible with the config as-written either, since there's no way to specify the number/format of dice rolled per spell level.

**Comment by johnnolan** [comment]
Would the feature work better if I expanded it to allow you to set your own dice rolls for each spell level? Example of how it would work is

- Add a `Cantip` option to the list
- Set default `Dice Formula` as currently works
- Allow users to add their own dice formula before the comparison and if exists use that formula instead of the default

![image](https://user-images.githubusercontent.com/5390820/221118090-5c18f710-a83b-4025-a452-91b0bc049dd8.png)

So the above image setup would

- For `Level 1` Spell roll with `advantage` and on a 1 trigger
- For `Level 2` Spell roll with `disadvantage` and on less than 3 trigger
- All other levels use `1d20` roll and check for the comparison

Would that solve your situation?

**Comment by linxcat** [comment]
Yes, that makes it fully definable. Though I would also change the title of the default roll to indicate that it is one.
